services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - w2meet-network
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DSN: ${PG_DSN}
      OXR_APP_ID: ${OXR_APP_ID}

    volumes:
        - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "exchangeuser", "-d", "exchange"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - w2meet-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PG_DSN=${PG_DSN}
      - TTL_SECONDS=${TTL_SECONDS}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./user-service:/app
    networks:
      - w2meet-network
  availability-service:
    build:
      context: ./availability-service
      dockerfile: Dockerfile
    environment:
      - USER_SERVICE_BASE=http://user-service:8000
    depends_on:
      user-service:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./availability-service:/app
    networks:
      - w2meet-network
  suggestion-service:
    build:
      context: ./suggestion-service
      dockerfile: Dockerfile
    environment:
      - AVAILABILITY_SERVICE_BASE=http://availability-service:8000
    depends_on:
      availability-service:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./suggestion-service:/app

    networks:
      - w2meet-network

networks:
  w2meet-network:
    driver: bridge

  