services:
  redis:
    image: redis:7-alpine
    container_name: ${REDIS_HOST}
    volumes:
    - redisdata:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - w2meet-network
  postgres:
    image: postgres:16-alpine
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 60s
      timeout: 3s
      retries: 10

    networks:
      - w2meet-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - w2meet-network
  gateway-service:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      user-service:
        condition: service_healthy
      availability-service:
        condition: service_healthy
      suggestion-service:
        condition: service_healthy
      worker-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - w2meet-network
    volumes:
      - ./gateway-service/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PG_DSN=${PG_DSN}
      - TTL_SECONDS=${TTL_SECONDS}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 70s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./user-service:/app
    networks:
      - w2meet-network
  availability-service:
    build:
      context: ./availability-service
      dockerfile: Dockerfile
    environment:
      - USER_SERVICE_BASE=${USER_SERVICE_BASE}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 80s
    depends_on:
      user-service:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./availability-service:/app
    networks:
      - w2meet-network
  suggestion-service:
    build:
      context: ./suggestion-service
      dockerfile: Dockerfile
    environment:
      - AVAILABILITY_SERVICE_BASE=${AVAILABILITY_SERVICE_BASE}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 90s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      availability-service:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./suggestion-service:/app

    networks:
      - w2meet-network
  worker-service:
    build:
      context: ./worker-service
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      QUEUE_NAME: ${QUEUE_NAME}
      SUGGESTION_BASE: ${SUGGESTION_BASE}
    depends_on:
      rabbitmq:
        condition: service_healthy
      suggestion-service:
        condition: service_healthy
    volumes:
      - ./worker-service:/app
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; socket.create_connection(('rabbitmq', 5672), 2)\""]
      interval: 100s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - w2meet-network
volumes:
  pg-data:
  redisdata:

networks:
  w2meet-network:
    driver: bridge

  